# Core
brew "antigen"
brew "ripgrep"
brew "zsh-history-substring-search"
brew "fzf"
brew "pidcat"
brew "tldr"
brew "wget"
brew "cloc"
brew "neovim"
brew 'zplug'

# Essential
brew "ldid"
brew "bundletool"
brew "libusbmuxd"
brew "libimobiledevice"
brew "ammonite-repl"


